# Generated by Django 5.2.4 on 2025-07-29 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/category/')),
            ],
        ),
        migrations.RenameField(
            model_name='tblcontact',
            old_name='massage',
            new_name='message',
        ),
        migrations.CreateModel(
            name='tblproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('product_info', models.TextField(null=True)),
                ('price', models.FloatField(null=True)),
                ('discounted_price', models.FloatField(null=True)),
                ('weight', models.CharField(max_length=80, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/product/')),
                ('posted_date', models.DateField(null=True)),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tblcategory')),
            ],
        ),
    ]
