# Generated by Django 5.2.4 on 2025-07-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tblcategory_rename_massage_tblcontact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblgallery',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
