# Generated by Django 5.2.4 on 2025-07-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_tblgallery_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblregister',
            fields=[
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/userpic/')),
                ('pincode', models.IntegerField(null=True)),
                ('landmark', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('regdate', models.DateField(null=True)),
            ],
        ),
    ]
