# Generated by Django 5.2.4 on 2025-08-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tblregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, null=True)),
                ('pid', models.CharField(max_length=50, null=True)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_picture', models.CharField(max_length=200, null=True)),
                ('product_info', models.TextField(null=True)),
                ('product_price', models.CharField(max_length=50, null=True)),
                ('discounted_price', models.CharField(max_length=50, null=True)),
                ('total_price', models.CharField(max_length=50, null=True)),
                ('product_weight', models.CharField(max_length=60, null=True)),
                ('product_quantity', models.CharField(max_length=50, null=True)),
                ('added_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, null=True)),
                ('pid', models.CharField(max_length=50, null=True)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_picture', models.CharField(max_length=200, null=True)),
                ('product_info', models.TextField(null=True)),
                ('product_price', models.CharField(max_length=50, null=True)),
                ('discounted_price', models.CharField(max_length=50, null=True)),
                ('total_price', models.CharField(max_length=50, null=True)),
                ('product_weight', models.CharField(max_length=60, null=True)),
                ('product_quantity', models.CharField(max_length=50, null=True)),
                ('added_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tblgallery',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
